# Generated by Django 2.2 on 2020-01-23 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltpython_app', '0002_auto_20200122_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('destination', models.CharField(max_length=100)),
                ('plan', models.TextField()),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('updated_at', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='beltpython_app.User')),
                ('user', models.ManyToManyField(related_name='trip', to='beltpython_app.User')),
            ],
        ),
    ]
