# Generated by Django 2.2 on 2020-01-24 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beltpython_app', '0004_auto_20200123_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_creator', to='beltpython_app.User'),
        ),
    ]
