# Generated by Django 2.2 on 2020-01-17 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows_app', '0003_show_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
