# Generated by Django 2.2 on 2020-01-21 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoreads_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
        migrations.RemoveField(
            model_name='author',
            name='note',
        ),
        migrations.AddField(
            model_name='author',
            name='my_dojo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='dojoreads_app.Book'),
        ),
    ]
