# Generated by Django 2.2 on 2020-01-21 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoreads_app', '0002_auto_20200121_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='my_dojo',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='dojoreads_app.Author'),
        ),
    ]
