# Generated by Django 2.2 on 2020-01-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoreads_app', '0003_auto_20200121_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='book',
            field=models.ManyToManyField(related_name='user', to='dojoreads_app.Book'),
        ),
    ]
