# Generated by Django 2.2 on 2020-01-22 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoreads_app', '0007_auto_20200121_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='dojoreads_app.User'),
        ),
    ]
